name: Update GitHub Repositories

on:
  workflow_dispatch:
    inputs:
      new_repos:
        description: "New repositories to add (comma-separated)"
        required: true
        type: string
        
permissions:
  contents: write  # Ensure GitHub Actions has write access to the repository
  
jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install -y jq

      - name: Validate Repositories
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          chmod +x azure/modules/githubrepo/validate_repos.sh
          MISSING_REPOS=$(./azure/modules/githubrepo/validate_repos.sh "${{ inputs.new_repos }}")
          
      - name: Debug MISSING_REPOS
        run: echo "Repositories to be created:'$MISSING_REPOS'"

      - name: Update Terraform File
        if: env.MISSING_REPOS != ''
        run: |
          chmod +x azure/modules/githubrepo/update_variables.sh
          ./azure/modules/githubrepo/update_variables.sh new_repo_name "${MISSING_REPOS//,/ }"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add variables.tf
          git commit -m "Auto-update Terraform variables"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

