name: Update GitHub Repositories

on:
  workflow_dispatch:
    inputs:
      new_repos:
        description: "New repositories to add (comma-separated)"
        required: true
        type: string

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install -y jq

      - name: Validate Repositories
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          chmod +x azure/modules/githubrepo/validate_repos.sh
          MISSING_REPOS=$(./azure/modules/githubrepo/validate_repos.sh "${{ inputs.new_repos }}")
          echo "MISSING_REPOS<<EOF" >> $GITHUB_ENV
          echo "$MISSING_REPOS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug MISSING_REPOS
        run: echo "Repositories to be created:'$MISSING_REPOS'"

      - name: Update Terraform File
        if: env.MISSING_REPOS != ''
        run: |
          chmod +x azure/modules/githubrepo/update_variables.sh
          ./azure/modules/githubrepo/update_variables.sh "$MISSING_REPOS"

